SAMPLE_RATE  = 50
WINDOW_SIZE  = 100
FFT_SIZE     = 128
PAD_SIZE     = FFT_SIZE - WINDOW_SIZE

NUM_PIXELS   = 8

FALL_SPIKE_THRESHOLD = 25.0
FALL_QUIET_THRESHOLD  = 2.0
FALL_QUIET_WINDOW     = 25

CLASS_STATIONARY = "STATIONARY"
CLASS_LIGHT      = "WALKING"
CLASS_INTENSE    = "JOGGING"
CLASS_SEIZURE    = "SEIZURE"
CLASS_FALL       = "FALL"

COLORS = {
    CLASS_STATIONARY : (0,   80,  255),
    CLASS_LIGHT      : (0,   200, 80),
    CLASS_INTENSE    : (255, 140, 0),
    CLASS_SEIZURE    : (255, 0,   0),
    CLASS_FALL       : (255, 80,  0),
}